apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-example
  namespace: default
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: eks-example
        image: 242337484181.dkr.ecr.ap-northeast-2.amazonaws.com/nodeapp:1.0.0 # {"$imagepolicy": "flux-system:nodeapp"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
