apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nodeapp
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: <your-acct-id>.dkr.ecr.<your-region>.amazonaws.com/nodeapp
  interval: 1m0s
